MAIN/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('', include('home.urls')),

] 


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index')
]

members/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as members_views

app_name = 'accounts'

urlpatterns = [
    path('register/',members_views.register, name='register'),
    #django will normaly look the login template in registration/login.html
    #we can create create it in the members App but we want to it this way
    path('login/',auth_views.LoginView.as_view(template_name='members/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='members/logout.html'), name='logout'),
    path('profile/',members_views.profile, name='profile'),
]

home/models.py
from django.db import models

# Create your models here.

members/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_images')

    def __str__(self):
        return f"{self.user.username} Profile"

members/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name','password1','password2']
        

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html',{})

members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegistrationForm
# Create your views here.

def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('first_name')
            messages.success(request, f'Profile de {user} créé avec succès')
            return redirect('index')
    else:
        form = UserRegistrationForm()
    return render(request, 'members/registerform.html',{'form':form})

@login_required
def profile(request):
    return render(request, 'members/profile.html')

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %} 
    <h1>Project is still under construction</h1>
{% endblock %}

members/templates/members/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="login-content">
        <form method="POST">
            {% csrf_token %}
            
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Pas encore enregistré? <a class="ml-2" href="{% url 'accounts:register'%}">Enregistrez-vous</a>
            </small>
        </div>
    </div>
{% endblock %}

members/templates/members/logout.html
{% extends 'base.html' %}

{% block content %}
    <h2>Vous avez été deconnecté avec success !</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            Se reconnecter? <a class="ml-2" href="{% url 'accounts:login'%}">Reconnectez-vous</a>
        </small>
    </div>

{% endblock %}

members/templates/members/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1> {{ user.first_name }} ! Welcome to your profile.</h1>
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.userprofile.image.url}}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.first_name }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>

    </div>
{% endblock %}

members/templates/members/registerform.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="registration-content">
        <form method="POST">
            {% csrf_token %}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Enregistement</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Enregistrez-vous</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                déjà enregistré? <a class="ml-2" href="{% url 'accounts:login'%}">connectez-vous</a>
            </small>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
    <title>Club des amis|{{ title }}</title>
    {% else %}
    <title>Club des amis</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet">
  </head>
  <body>

    {% include 'header.html' %}
    
    <div class="container col-md-8">
        <br>

        {% if messages %}

            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}

        {% endif %}

        {% block content %} {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

templates/header.html
  <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">Club Des Amis</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Nos Video</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Nous Contacter</a>
          </li>
          
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' %}">Profile</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        
      </div>
    </div>
  </nav>